export const CLIENT_GATEWAY = Symbol('CLIENT_GATEWAY');
export const CLIENT_CONTROLLER = Symbol('CLIENT_CONTROLLER');
export const GET_CLIENT_USE_CASE = Symbol('GET_CLIENT_USE_CASE');
export const CREATE_CLIENT_USE_CASE = Symbol('CREATE_CLIENT_USE_CASE');