export const ORDER_CONTROLLER = Symbol('ORDER_CONTROLLER');
export const ORDER_GATEWAY = Symbol('ORDER_GATEWAY');
export const FAKE_NOTIFY_ORDER_GATEWAY = Symbol('FAKE_NOTIFY_ORDER_GATEWAY');
export const PAYMENT_ORDER_USE_CASE = Symbol('PAYMENT_ORDER_USE_CASE');
export const CREATE_ORDER_USE_CASE = Symbol('CREATE_ORDER_USE_CASE');
export const GET_ORDER_USE_CASE = Symbol('GET_ORDER_USE_CASE');
export const UPDATE_ORDER_STATUS_USE_CASE = Symbol('UPDATE_ORDER_STATUS_USE_CASE');
export const UPDATE_ORDER_PAYMENT_USE_CASE = Symbol('UPDATE_ORDER_PAYMENT_USE_CASE');
