export const ORDER_CONTROLLER = Symbol('ORDER_CONTROLLER');
export const CREATE_ORDER_SERVICE = Symbol('CREATE_ORDER_SERVICE');
export const GET_ORDER_SERVICE = Symbol('GET_ORDER_SERVICE');
export const UPDATE_ORDER_STATUS_USE_CASE = Symbol(
	'UPDATE_ORDER_STATUS_USE_CASE'
);
export const UPDATE_ORDER_PAYMENT_USE_CASE = Symbol(
	'UPDATE_ORDER_PAYMENT_USE_CASE'
);
